# Site settings
title: CMSC320 (Spring 2016)
email: hcorrada@umiacs.umd.edu
description: "CMSC320, Introduction to Data Science"
baseurl: "/IntroDataSci"
twitter_username: hcorrada
github_username:  hcorrada
ignore: ["materials", "tasks"]

pageOrder: ["/index.html", "/resources.html","/syllabus.html","/projects.html"]

# Build settings
markdown: kramdown
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# my variables
piazza_url: "https://piazza.com/class/ije6l0thr383ii"
elms_url: "https://myelms.umd.edu/courses/1177854"
