# Site settings
title: CMSC320 Introduction to Data Science
email: hcorrada@umiacs.umd.edu
description: >
  A description will be added here
baseurl: "/IntroDataSci"
url: "http://hcbravo.org"
fixedNav: 'true' # true or false
theme: orange # green, blue, orange, purple, grey
twitterUsername: hcorrada
githubUsername: hcorrada
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
