# Site settings
title: CMSC320 Introduction to Data Science
author: Héctor Corrada Bravo
theme_author: Alex Carpenter
theme_url: "http://alexcarpenter.me/material-jekyll-theme/"
email: hcorrada@umiacs.umd.edu
description: >
  A description will be added here
baseurl: "/IntroDataSci"
url: "http://hcbravo.org"
fixedNav: 'true' # true or false
theme: orange # green, blue, orange, purple, grey
twitterUsername: hcorrada
githubUsername: hcorrada
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, materials, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

# course variables
piazza_url: "https://piazza.com/class/ije6l0thr383ii"
elms_url: "https://myelms.umd.edu/courses/1177854"
